django/api/urls.py
from django.conf.urls import patterns, include, url
from api import attendance
from api import availability
from api import course
from api import review
from api import student_to_class
from api import study_session
from api import utils

urlpatterns = patterns('',
    url(r'^Attendance/future$',                     attendance.get_future_attendances,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Attendance/past$',                       attendance.get_past_attendances,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Attendance/accepted$',                   attendance.get_accepted_attendances,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Attendance/declined$',                   attendance.get_accepted_attendances,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Attendance/no_rsvp$',                    attendance.get_suggested_attendances,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Attendance/rsvp$',                       attendance.set_attendance_rsvp,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Attendance/my_children$',                attendance.my_children,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),
                                                    
    url(r'^Availability/current$',                  availability.get_user_availabilities,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Availability/set$',                      availability.set_availabilities,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Availability/optimal_times$',            availability.get_optimal_times,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Class/prefixes$',                        course.get_class_prefixes,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Class/my_classes$',                      course.get_my_classes,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^StudentToClass/add_class$',              student_to_class.add_class,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^StudentToClass/remove_class$',           student_to_class.remove_class,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^StudySession/dummy$',                    study_session.study_session_dummy),

    url(r'^StudySession/protected_dummy$',          study_session.study_session_protected_dummy, 
                                                    kwargs={'backend': 'google-oauth2'},
                                                    name='study_session_protected_dummy'),

    url(r'^StudySession/view$',                     study_session.study_session_view,
                                                    name='study_session_view'),

    url(r'^StudySession/create$',                   study_session.create_study_session, 
                                                    kwargs={'backend': 'google-oauth2'}, 
                                                    name='create_study_session'),

    url(r'^StudySession/search$',                   study_session.search, 
                                                    kwargs={'backend': 'google-oauth2'}
                                                    ),

    url(r'^StudySession/rsvp$',                     study_session.rsvp, 
                                                    kwargs={'backend': 'google-oauth2'}
                                                    ),

    url(r'^StudySession/my_children$',              study_session.get_child_study_sessions,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^StudySession/past_children$',            study_session.get_past_child_study_sessions,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^StudySession/remove$',                   study_session.remove,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Review/create$',                         review.create_review,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^Review/get$',                            review.get_reviews,
                                                    kwargs={'backend': 'google-oauth2'},
                                                    ),

    url(r'^oauth2/callback/(?P<backend>[^/]+)/$',   utils.oauth2_callback,      name='oauth2_callback'),
    url(r'^manual_login/(?P<backend>[^/]+)/$',      utils.register_manually,    name='oauth2_manual'),
)

django/studybuddy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studybuddy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls')),
    #url(r'^complete/(?P<backend>[^/]+)/$', 'api.views.oauth2_callback', name='oauth2_callback'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^webapp/', include('webapp.urls')),
)

django/webapp/urls.py
__author__ = 'androideka'

from django.conf.urls import patterns, url

from webapp import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^create/', views.ss_create, name='create_study_session'),
    url(r'^availabilities/', views.manage_availabilities, name='manage_availabilities'),
    url(r'^classes/', views.manage_classes, name='manage_classes'),
    url(r'^review/', views.review_sessions, name='review_sessions'),
    url(r'^search/', views.search, name='search'),
    url(r'^children/', views.children, name='children'),
    url(r'^(?P<ss_id>\d+)/reviews/$', views.ss_review, name='reviews'),
)

django/api/models.py
from django.db import models
from django.db.models.signals import post_init
from django.contrib.auth.models import User
import json

class Class(models.Model):
    class_prefixes = (
        ("COMS", "COMS"), ("CPRE", "CPRE"), ("MATH", "MATH"),
        ("STAT", "STAT"), ("ENGL", "ENGL"), ("PHIL", "PHIL"),
        ("AMIN", "AMIN"), ("PHYS", "PHYS"), ("CHEM", "CHEM"),
        )

    prefix      = models.CharField(max_length=4, choices=class_prefixes)
    number      = models.IntegerField()

    def __unicode__(self):
        return "{0} {1}".format(self.prefix, self.number)

    def get_json(self):
        data =  { "class_prefix" : self.prefix,
                  "class_number" : self.number }
        return data


class UserProfile(models.Model):
    choices = (
        (0, "Student"),
        (1, "TA"),
        (2, "Business"),
        )

    user            = models.ForeignKey(User)
    agency          = models.IntegerField(choices=choices)

    def __unicode__(self):
        return "{0}: {1}".format(self.user, self.agency)


class StudentToClass(models.Model):
    user            = models.ForeignKey(User)
    course          = models.ForeignKey(Class)    
    is_ta           = models.BooleanField(blank=False, default=False)

    def __unicode__(self):
        return "{0} -> {1}".format(self.user, self.course)

    def get_json(self):
        data =  {
                    "user"       : str(self.user),
                    "course"     : self.course.get_json(),
                    "is_ta"      : self.is_ta,
                }
        return data


class StudySession(models.Model):
    parent_class    = models.ForeignKey(Class)
    author          = models.ForeignKey(User)
    start_time      = models.DateTimeField()
    end_time        = models.DateTimeField()
    description     = models.CharField(max_length=256)
    location        = models.CharField(max_length=256)
    latitude        = models.FloatField(blank=True, null=True)
    longitude       = models.FloatField(blank=True, null=True)
    is_ta           = models.BooleanField(blank=False, default=False)

    def __unicode__(self):
        return "{0} by {1}".format(self.parent_class, self.author)

    def get_json(self):
        data =  { 
                    "parent_class" : self.parent_class.get_json(),
                    "author"       : str(self.author),
                    "start_time"   : self.start_time.isoformat(),
                    "end_time"     : self.end_time.isoformat(),
                    "description"  : self.description,
                    "location"     : self.location,
                    "latitude"     : self.latitude,
                    "longitude"    : self.longitude,
                    "id"           : self.id,
                    "is_ta"        : self.is_ta,
                }
        return data


class Review(models.Model):
    text            = models.CharField(max_length=512)
    rating          = models.IntegerField(choices=( (1,1), (2,2), (3,3), 
                                                    (4,4), (5,5) ))
    author          = models.ForeignKey(User)
    study_session   = models.ForeignKey(StudySession)

    def __unicode__(self):
        return "({0}) - {1}".format(self.rating, self.study_session)

    def get_json(self):
        data =  {
                    "text"          : self.text,
                    "rating"        : self.rating,
                    "author"        : str(self.author),
                    "study_session" : self.study_session.get_json(),
                }
        return data


class Attendance(models.Model):
    choices         = ( (0, "None"),
                        (1, "Accepted"),
                        (2, "Declined") )
    user            = models.ForeignKey(User)
    study_session   = models.ForeignKey(StudySession)
    rsvp_status     = models.IntegerField(choices=(choices))

    start_time      = models.DateTimeField(blank=True, null=True)

    def has_review(self):
        review_list = Review.objects.filter(author=self.user, study_session=self.study_session)
        return bool(len(review_list) > 0)

    def __unicode__(self):
        return "{0} - {1}".format(self.choices[self.rsvp_status][1], self.study_session)

    def get_json(self):
        data =  {
                    "user"          : str(self.user),
                    "study_session" : self.study_session.get_json(),
                    "rsvp_status"   : self.rsvp_status,
                    "id"            : self.id,
                    "has_review"    : self.has_review(),
                }
        return data


class Availability(models.Model):
    choices         = ( (0, "Monday"),
                        (1, "Tuesday"),
                        (2, "Wednesday"),
                        (3, "Thursday"),
                        (4, "Friday"),
                        (5, "Saturday"),
                        (6, "Sunday") )

    day             = models.IntegerField(choices=(choices))
    user            = models.ForeignKey(User)
    start           = models.TimeField()
    end             = models.TimeField()

    def __unicode__(self):
        return "{0} {1} - {2}".format( self.user, self.choices[self.day][1], self.start.isoformat())

    def get_json(self):
        data =  {
                    "day"   : self.day,
                    "user"  : str(self.user),
                    "start" : self.start.__format__("%H:%M"),
                    "end"   : self.end.__format__("%H:%M"),
                }
        return data


def set_attendance_start_time(sender, **kwargs):
    instance = kwargs['instance']
    instance.start_time = instance.study_session.start_time


post_init.connect(set_attendance_start_time, sender=Attendance)

django/webapp/models.py
from django.db import models

# Create your models here.

django/webapp/templates/webapp/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}Study Buddy{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}"/>
</head>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<body>
<div class="wrapper">
    <div class="nav">
        <ul class="nav">
            <li class="nav-tabs">{% block nav_home %}<a href="/webapp/">Home</a>{% endblock %}</li>
            <li class="nav-tabs">{% block nav_create %}<a href="/webapp/create/">Create a Session</a>{% endblock %}</li>
            <li class="nav-tabs">{% block nav_classes %}<a href="/webapp/classes">Manage My Classes</a>{% endblock %}</li>
            <li class="nav-tabs">{% block nav_avail %}<a href="/webapp/availabilities">Manage Availabilities</a>{% endblock %}</li>
            <li class="nav-tabs">{% block nav_review %}<a href="/webapp/review">Review My Sessions</a>{% endblock %}</li>
            <li class="nav-tabs">{% block nav_my_reviews %}<a href="/webapp/children">See My Sessions</a>{% endblock %}</li>
            <li class="nav-tabs">{% block nav_search %}<a href="/webapp/search">Search</a>{% endblock %}</li>
        </ul>
    </div>
    <div>
        {% block body_block %}Default Content
        {% endblock %}
    </div>
</div>
</body>
</html>

django/webapp/templates/webapp/children.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy - See My Reviews{% endblock %}

{% block nav_my_reviews %}<strong>See My Sessions</strong>{% endblock %}

{% block body_block %}

<table class="table-condensed">
    <tr>
        <td><b>Class Name</b></td>
        <td><b>Start Time</b></td>
        <td><b>End Time</b></td>
        <td><b>Description</b></td>
        <td><b>Location</b></td>
        <td><b>Reviews</b></td>
    </tr>
    {% for ss in my_ss_list %}
    <tr>
        <td>{{ ss.parent_class }}</td>
        <td>{{ ss.start_time }}</td>
        <td>{{ ss.end_time }}</td>
        <td>{{ ss.description }}</td>
        <td>{{ ss.location }}</td>
        <td><a href="/webapp/{{ss.id}}/reviews">See Reviews</a></td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

django/webapp/templates/webapp/create_study_session.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy - Create Session{% endblock %}

{% block nav_create %}<strong>Create a Session</strong>{% endblock %}

{% block body_block %}

<script>
$(function() {
    $( "#start_day" ).datepicker();
});
</script>
<script>
$(function() {
    $( "#end_day" ).datepicker();
});
</script>

<div class="content" data-role="none" data-enhancement="False">
    {% if message %}<b>{{ message }}</b>{% endif %}

    <form method="post" action="{% url 'create_study_session' %}" id="create_form">
        {% csrf_token %}
        <table class="table-condensed">
            <tr>
                <td>Class Prefix</td>
                <td><input type="text" name="class_prefix" id="class_prefix" required="true"></td>
            </tr>
            <tr>
                <td>Class Number</td>
                <td><input type="text" name="class_number" id="class_number" required="true"></td>
            </tr>
            <tr>
                <td>Start Day</td>
                <td><input type="text" name="start_day" id="start_day" required="true"></td>
            </tr>
            <tr>
                <td>Start Time</td>
                <td><input type="text"  name="start_time" id="start_time" required="true"></td>
            </tr>
            <tr>
                <td>End Day</td>
                <td><input type="text" name="end_day" id="end_day" required="true"></td>
            </tr>
            <tr>
                <td>End Time</td>
                <td><input type="text" name="end_time" id="end_time" required="true"></td>
            </tr>
            <tr>
                <td>Description</td>
                <td><input type="text" name="description" id="description" required="true"></td>
            </tr>
            <tr>
                <td>Location</td>
                <td><input type="text" name="location" id="location" required="true"></td>
            </tr>
            <tr>
                <td>Latitude</td>
                <td><input type="text" name="latitude" id="latitude"></td>
            </tr>
            <tr>
                <td>Longitude</td>
                <td><input type="text" name="longitude" id="longitude"></td>
            </tr>
            <tr>
                <td><input type="submit" value="Create Session" id="create_session"></td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

django/webapp/templates/webapp/manage_availabilities.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy - Manage Availabilities{% endblock %}

{% block nav_avail %}<strong>Manage Availabilities</strong>{% endblock %}

{% block body_block %}

{% if message %}<strong> {{ message }} </strong>{% endif %}
{% if error_message %}<strong> {{ error_message }} </strong>{% endif %}

<strong>Current Availabilities</strong>
<table class="table-hover">
{% for avail in availabilities %}
    <tr>
        <form method="post" action="{% url 'manage_availabilities' %}">
            {% csrf_token %}
            <input type="hidden" name="availability_id" value="{{ avail.id }}">
            <td>
                Day: <input type="text" name="day" id="day_{{ avail.id }}" value="{{avail.get_day_display}}">
            </td>
            <td>
                Start: <input type="text" name="start_time" id="end_time{{ avail.id }}" value="{{avail.start}}">
            </td>
            <td>
                End: <input type="text" name="end_time" id="end_time{{ avail.id }}" value="{{avail.end}}">
            </td>
            <td>
                <input class="btn" type="submit" value="Delete" name="delete">
            </td>
        </form>
    <tr>
{% endfor %}
</table>

<br>
<strong>Add new availability</strong>
<form method="post" action="{% url 'manage_availabilities' %}">
    {% csrf_token %}
    <table class="table-condensed">
        <tr>
            <input type="hidden" name="availability_id" value="{{ avail.id }}" required="true">
            <td>
                Day: <input type="text" name="day" value="{{avail.day}}" required="true">
            </td>
            <td>
                Start: <input type="text" name="start_time" value="{{avail.start}}" required="true">
            </td>
            <td>
                End: <input type="text" name="end_time" value="{{avail.end}}" required="true">
            </td>
            <td>
                <input class="btn" type="submit" value="Add" name="add">
            </td>
        </tr>
    </table>
</form>
{% endblock %}

django/webapp/templates/webapp/manage_classes.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy - Manage Classes{% endblock %}

{% block nav_classes %}<strong>Manage Your Classes</strong>{% endblock %}

{% block body_block %}

{% if message %}<strong> {{ message }} </strong>{% endif %}

<table class="table-condensed">
    {% for stc in classes %}
    <tr>
        <td>
            <strong>Class:</strong> {{ stc.course.prefix }} {{ stc.course.number }}
        </td>
        <td>
            <form method="post" action="{% url 'manage_classes' %}" id="{{ stc.id }}">
                {% csrf_token %}
                <button class="btn" name="remove" type="submit" value="{{ stc.id }}">Remove</button>
            </form>
        </td>
    </tr>
    {% endfor %}
</table>
<form method="post" action="{% url 'manage_classes' %}">
    {% csrf_token %}
    <table class="table-condensed">
        <tr>
            <td>Class Prefix</td>
            <td><input type="text" name="class_prefix" id="class_prefix" required="true"></td>
        </tr>
        <tr>
            <td>Class Number</td>
            <td><input type="text" name="class_number" id="class_number" required="true"></td>
        </tr>
        <tr>
            <td>Are you a TA for this class?</td>
            <td><input class="checkbox-inline" type="checkbox" name="is_ta" id="is_ta"></td>
        </tr>
    </table>
    <input class="btn" name="add" type="submit" value="Add Class">
</form>
{% endblock %}

django/webapp/templates/webapp/review_study_session.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy - Review Your Sessions{% endblock %}

{% block nav_review %}<strong>Review Your Sessions</strong>{% endblock %}

<link rel="stylesheet" type="text/css" href="jRating.jquery.css" media="screen" />
<script type="text/javascript" src="jRating.jquery.js"></script>

<script type="text/javascript">
jQuery(document).ready(function(){
      $(".rating").jRating();
});
</script>

{% block body_block %}
    <table class="table-condensed">
        <tr>
            <td><b>Class</b></td>
            <td><b>Date</b></td>
            <td><b>Creator</b></td>
            <td><b>Description</b></td>
            <td><b>Rating 1-5</b></td>
            <td><b>Feedback</b></td>
        </tr>
        {% for att in past_attendances %}
        {% if att.rsvp_status == 1 %}
        <form method="post" action="{% url 'review_sessions' %}">
        {% csrf_token %}
        <tr>
            <td>{{att.study_session.parent_class}}</td>
            <td>{{att.study_session.start_time}}</td>
            <td>{{att.study_session.author}}</td>
            <td>{{att.study_session.description}}</td>
            <td>
                <div style="width: 120px">
                <input class="radio-inline" type="radio" name="rating" value="1"/>
                <input class="radio-inline" type="radio" name="rating" value="2"/>
                <input class="radio-inline" type="radio" name="rating" value="3"/>
                <input class="radio-inline" type="radio" name="rating" value="4"/>
                <input class="radio-inline" type="radio" name="rating" value="5"/>
                </div>
            </td>
            <td><input type="text" name="text" id="text" value="Optional Description"/></td>
            <td><input class="btn" type="submit" value="Review"/></td>
            <td><input type="text" name="attendance_id" id="attendance_id" value="{{ att.id }}" style="visibility: hidden;width:0px;"/></td>
        </tr>
        </form>
        {% endif %}
        {% endfor %}
    </table>
{% endblock %}

django/webapp/templates/webapp/reviews.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy{% endblock %}

{% block body_block %}

<table class="table-condensed">
<tr>
    <td><b>Author</b></td>
    <td><b>Rating</b></td>
    <td><b>Description</b></td>
    <td><b>Class</b></td>
    <td><b>Session Description</b></td>
</tr>
{% for review in review_list %}
<tr>
    <td>{{ review.author }}</td>
    <td>{{ review.rating }}</td>
    <td>{{ review.text }}</td>
    <td>{{ review.study_session.parent_class }}</td>
    <td>{{ review.study_session.description }}</td>
</tr>
{% endfor %}
</table>

{% endblock %}

django/webapp/templates/webapp/search.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy - Search for Study Sessions{% endblock %}

{% block nav_search %}<b>Search</b>{% endblock %}


{% block body_block %}
{% if message %}<b> {{ message }} </b>{% endif %}
<form method="post" action="{% url 'search' %}" id="search_form">
    {% csrf_token %}
    <table class="table-condensed">
        <tr>
            <td>Class Prefix (COMS, MATH, etc)</td>
            <td><input type="text" id="class_prefix" name="class_prefix"/></td>
        </tr>
        <tr>
            <td>Class Number (227, 101, etc)</td>
            <td><input type="text" id="class_number" name="class_number"/></td>
        </tr>
        <tr>
            <td><input type="submit" id="search_sessions" value="Search"/></td>
        </tr>
    </table>
</form>
{% if message == "" %}
<hr/>
<table class="table-condensed">
    <tr>
        <td><b>Class Name</b></td>
        <td><b>Start Time</b></td>
        <td><b>End Time</b></td>
        <td><b>Description</b></td>
        <td><b>Location</b></td>
        <td><b>RSVP</b></td>
    </tr>
    {% for session in search_results %}
        <tr>
            <td>{{ session.parent_class }}</td>
            <td>{{ session.start_time }}</td>
            <td>{{ session.end_time }}</td>
            <td>{{ session.description }}</td>
            <td>{{ session.location }}</td>
            <td>
                <form method="post" action="{% url 'search' %}" id="{{ session.id }}">
                    {% csrf_token %}
                    <input type="hidden" name="rsvp" value="{{ session.id }}">
                    <button class="btn" name="accept" type="submit" value="{{ session.id }}">Accept</button>
                </form>
            </td>
        </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}

django/webapp/templates/webapp/view_study_session.html
{% extends 'webapp/base.html' %}
{% block title %}Study Buddy - View Sessions{% endblock %}

{% block nav_home %}<strong>Home</strong>{% endblock %}

{% block body_block %}

<style>
    {% for att in attendances %}
    {% if att.study_session.rsvp_status != 2 and att.study_session.latitude and att.study_session.longitude %}
    #map-canvas-{{att.study_session.id}} {
        width: 150px;
        height: 150px;
    }
    {% endif %}
    {% endfor %}
</style>

<body>
	<div class="content" data-role="none" data-enhancement="False">
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

		<table class="table-hover">
			<tr>
                <td><b>Class Name</b></td>
                <td><b>Start Time</b></td>
                <td><b>End Time</b></td>
                <td><b>Description</b></td>
                <td><b>Location</b></td>
                <td><b>Map</b></td>
                <td><b>RSVP</b></td>
			</tr>
			{% for attendance in attendances %}
            {% if attendance.rsvp_status == 1 %}
			<tr>
				<td>{{attendance.study_session.parent_class}}</td>
				<td>{{attendance.study_session.start_time}}</td>
				<td>{{attendance.study_session.end_time}}</td>
				<td>{{attendance.study_session.description}}</td>
				<td>{{attendance.study_session.location}}</td>
                <td><div id="map-canvas-{{attendance.study_session.id}}"></div></td>
                <td>
                    <form method="post" action="{% url 'index' %}" id="{{ attendance.id }}">
                        {% csrf_token %}
                        <button class="btn" name="decline" type="submit" value="{{ attendance.id }}">Decline</button>
                    </form>
                </td>
			</tr>
            {% endif %}
			{% endfor %}
            {% for attendance in attendances %}
            {% if attendance.rsvp_status != 1 %}
			<tr>
				<td>{{attendance.study_session.parent_class}}</td>
				<td>{{attendance.study_session.start_time}}</td>
				<td>{{attendance.study_session.end_time}}</td>
				<td>{{attendance.study_session.description}}</td>
				<td>{{attendance.study_session.location}}</td>
                <td><div id="map-canvas-{{attendance.study_session.id}}"></div></td>
                <td>
                    <form method="post" action="{% url 'index' %}" id="{{ attendance.id }}">
                        {% csrf_token %}
                        {% if attendance.rsvp_status == 0 or attendance.rsvp_status == 2 %}
                        <button class="btn" name="accept" type="submit" value="{{ attendance.id }}">Accept</button>
                        {% else %}
                        <button class="btn" name="decline" type="submit" value="{{ attendance.id }}">Decline</button>
                        {% endif %}
                    </form>
                </td>
			</tr>
            {% endif %}
			{% endfor %}
		</table>
		<br>

</div>
</body>
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script type="text/javascript">
    function initialize() {
        {% for att in attendances %}
        {% if att.rsvp_status != 2 and att.study_session.longitude and att.study_session.latitude %}
        var mapCanvas_{{att.study_session.id}} = document.getElementById('map-canvas-{{att.study_session.id}}');
        var mapOptions_{{att.study_session.id}} = {
            center: new google.maps.LatLng({{att.study_session.latitude}}, {{att.study_session.longitude}}),
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map_{{att.study_session.id}} = new google.maps.Map(mapCanvas_{{att.study_session.id}}, mapOptions_{{att.study_session.id}})
        {% endif %}
        {% endfor %}
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

{% endblock %}